title: "Lama's Portfolio"
subtitle: "Business Analyst | Data Enthusiast"
email: "laljurai@purdue.edu"
description: "Welcome! Explore my journey in data-driven insights and impactful projects. Let’s dive into the world of business analysis together!"

social:
  linkedin: "https://linkedin.com/in/lamaaljuraisi"
  github: "https://github.com/lamajuraisi"
  
# Tile or post settings (if needed for the theme’s homepage display)
tiles-source: pages  # Options: "posts" or "pages"
tiles-count: 6  # Number of tiles to display

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
