# site settings
title: Lama's Protifolio
subtitle:
email: lama.juraisy@gmail.com
description: Hi there! I’m Lama, a Business Analyst passionate about using data to drive insights and make a real impact. Throughout my career, I've worked on projects that blend strategic analysis with technical skills, like data visualization and automation. 
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
